return {
	opt = {
		fileencoding = "utf-8",
		cmdheight = 0,
		number = true,
		relativenumber = true,
		history = 100,
		termguicolors = true,
		filetype = "on",
		cursorline = true,
		foldenable = true,
		foldlevel = 99,
		foldlevelstart = 99,
		ignorecase = true,
		shiftwidth = 2,
		showtabline = 0,
		tabstop = 2,
		expandtab = true,
		wrap = false,
		writebackup = false,
		laststatus = 0,
		updatetime = 200,
		fillchars = "eob: ",
		modeline = false,
		conceallevel = 2,
		mouse = "",
		clipboard = "unnamedplus",
	},

	g = {
		mapleader = " ",
		highlighturl_enabled = true,
	},
}
