-- return {
-- {
-- 	"vhyrro/luarocks.nvim",
-- 	priority = 1000,
-- 	config = true,
-- 	opts = {
-- 		rocks = { "lua-curl", "nvim-nio", "mimetypes", "xml2lua" },
-- 	},
-- },
-- {
-- 	"rest-nvim/rest.nvim",
-- 	ft = "http",
-- 	config = function()
-- 		require("rest-nvim").setup()
-- 	end,
-- },
-- }
